// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pnpjtkqltiojqudoxqsj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBucGp0a3FsdGlvanF1ZG94cXNqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc1NzUzMDMsImV4cCI6MjA2MzE1MTMwM30.3NlL7-EY8s2UhpMNyJxB2ZjL_XW-lYNDOYNry70v-7E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);